parameters:
  displayName: ''
  workingDirectory: ''
  project: ''
  scheme: ''

jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macos-latest'

    variables:
      - group: AgoraKeys

    steps:
      - script: cd ${{ parameters.workingDirectory }} && ls && python ci.env.py && ls
        env:
          AGORA_APP_ID: $(agora.appId)
          File_Directory: '${{ parameters.project }}'
            
      - task: InstallAppleCertificate@2
        inputs:
          certSecureFile: 'App.p12'
          certPwd: $(agora.password)

      - task: InstallAppleProvisioningProfile@1
        inputs:
          provProfileSecureFile: 'App.mobileprovision'

      - script: cd 'cicd/scripts' && chmod +x ios_build.sh && ./ios_build.sh ../../${{ parameters.workingDirectory }} '${{ parameters.project }}' '${{ parameters.scheme }}'
        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '${{ parameters.workingDirectory }}/${{ parameters.project }}.ipa'
          ArtifactName: ${{ parameters.displayName }}
