# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scene-Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'AgoraRtm_iOS', '~> 1.4.8'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AgoraRtcEngine_iOS_Preview', '4.0.0.preview.3'
  # Pods for Scene-Examples

end
