# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def commonPods
  use_frameworks!
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'RxRelay', '6.1.0'
  pod 'IGListKit', '~> 4.0.0'
end

target 'Core' do
  commonPods
  use_frameworks!
end

target 'InteractivePodcast' do
  commonPods
  use_frameworks!
  pod 'AgoraRtcEngine_iOS'
end

target 'BlindDate' do
  commonPods
  use_frameworks!
  pod 'AgoraRtm_iOS'
  pod 'AgoraRtcEngine_iOS'
end

# target with leancloud sdk
target 'Scene-Examples_LeanCloud' do
  commonPods
  use_frameworks!
  pod 'LeanCloud'
end

# target with firebase sdk
target 'Scene-Examples_Firebase' do
  commonPods
  use_frameworks!
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
end
