# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
#source 'https://cdn.cocoapods.org/'

#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'Scene-Examples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'AgoraRtcEngine_iOS_Preview', '4.0.0.preview.3'
#  pod 'AgoraScreenShare', :path => 'sdk'
  pod 'Agora-Scene-Utils', '~> 1.0.2'
#  pod 'AgoraSyncManager', '1.0.2'
  pod 'AgoraSyncManager', :path => 'AgoraSyncManager'
  # Pods for Scene-Examples

end
